name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang, msvc]
        exclude:
          - os: ubuntu-latest
            compiler: msvc
          - os: macos-latest
            compiler: msvc

    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.compiler }}

    steps:
      - uses: actions/checkout@v2

      - name: Run the tests
        run: ./command/test.sh

  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install the tools
        run: sudo apt install cppcheck clang-tidy -y

      - name: Run cppcheck
        run: cppcheck optiscope.c --force

      - name: Run clang-tidy
        run: clang-tidy optiscope.c

      - name: Run GCC -fanalyzer
        run: gcc optiscope.c -c -o /dev/null -fanalyzer -Wno-analyzer-malloc-leak || true

  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Hyperfine
        run: cargo install hyperfine

      - name: Run the benchmarks
        run: ./command/bench.sh
